### ISSUE TITLE
PGN export is broken on Python 2.7

### ISSUE THREAD

**Issue by lucasart** [lucasart/zinc#22]
seems to be a library issue. need to investigate this further.

**Comment by AndyGrant** [comment]
I seem to have no issue with the PGN exports. I am able to run the program, set PgnOut, and have the pgn files saved after all games have been played.

Works on the following setups for me:
  Windows7-64bit using python2.7.8
  Ubuntu14-32bit using python2.7.6
  Ubuntu14-32bit using python3.4.3

If it works in 2.7 for me, on windows of all things, then i would have to guess it is a non-python27 issue. 

If you don't already have a solution, do you mind posting more about the issue?

Thanks, Andrew Grant

**Comment by lucasart** [comment]
sure, here's the error:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "./zinc.py", line 337, in play_games
    pgnOut, job.round)
  File "./zinc.py", line 254, in play_game
    game = chess.pgn.Game.from_board(board)
AttributeError: type object 'Game' has no attribute 'from_board'
```

**Comment by AndyGrant** [comment]
I cannot seem to reproduce the issue.

The only thought I have is that it has to do something with the @classmethod attached to the pgn.Game.from_board method. I don't expect this to be the issue, but is it possible that it is trying to call from_board on your own Game class that you wrote? Maybe add a from_board to your Game class and see if it is called.

Other than that, I have no clue and no means of investigating without just taking guesses.

**Comment by lucasart** [comment]
I removed the Game class. Problem persists. Oh well, I guess I'll just use Python 3 and live with it.

**Comment by AndyGrant** [comment]
You could write your own implementation of from_ board, and bypass the library's one. 

Either way, this is a interesting issue. I spent some time looking for answers and made very little headway.

**Comment by lucasart** [comment]
I think I found a possible explanation for this issue:
```
lucas@megatron:~$ pip3 list|grep python-chess
python-chess (0.14.1)
lucas@megatron:~$ pip list|grep python-chess
python-chess (0.13.1)
```
Now I just need to have a look at the code of python-chess version 0.13.1, to confirm that Game.from_board() is missing.
